require 'ffi'

require 'gsl/gsl'

require 'gsl/helper'
require 'gsl/attach_dsl'

require 'gsl/error'

require 'gsl/vector'
require 'gsl/vector/char'
require 'gsl/vector/complex'
require 'gsl/vector/complex/float'
#require 'gsl/vector/complex/long_double'
require 'gsl/vector/double'
require 'gsl/vector/float'
require 'gsl/vector/int'
#require 'gsl/vector/long_double'
require 'gsl/vector/long'
require 'gsl/vector/short'
require 'gsl/vector/uchar'
require 'gsl/vector/uint'
require 'gsl/vector/ulong'
require 'gsl/vector/uchar'
require 'gsl/vector/ushort'

require 'gsl/matrix'
require 'gsl/matrix/char'
require 'gsl/matrix/complex'
require 'gsl/matrix/complex/float'
#require 'gsl/matrix/complex/long_double'
require 'gsl/matrix/double'
require 'gsl/matrix/float'
require 'gsl/matrix/int'
#require 'gsl/matrix/long_double'
require 'gsl/matrix/long'
require 'gsl/matrix/short'
require 'gsl/matrix/uchar'
require 'gsl/matrix/uint'
require 'gsl/matrix/ulong'
require 'gsl/matrix/uchar'
require 'gsl/matrix/ushort'


#require 'gsl/error'
#require 'gsl/vector'
#require 'gsl/matrix'

require 'gsl/symbols'
